name: CICD

on: 
  workflow_dispatch:



jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Code commited to the branch"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code build to the Docker
        run: echo "Docker Conatiner build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code test in the docker
        run: echo "Testing the Container"
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Deploy
        run: echo "Docker compose deployed the app"
