name: hello

on: 
  # push:
  #   branches: [main]

  #   paths: 
  #     - '**.html'
  workflow_dispatch:
    


jobs:
  greets:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to the user
        run: echo "Hello Shuvradeep"

      - name: say hello to the username
        run: echo "Hello $RUNNER_OS"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: Want to know the Version of Python and docker
        run: docker --version && python --version
    
